### ISSUE TITLE
There are 2 characters without pyingyin

### ISSUE THREAD

**Issue by euberdeveloper** [ruddfawcett/hanziDB.csv#1]
There are 2 characters without pyingin:

- freq. rank `8220`, character `裏`
- freq. rank `9019`, character `秊`

```
{
  frequency_rank: '8220',
  charcter: '裏',
  pinyin: null,
  definition: 'inside, interior, within',
  radical: '衣',
  radical_code: '145.7',
  stroke_count: '13',
  hsk_levl: null,
  general_standard_num: null
}
{
  frequency_rank: '9019',
  charcter: '秊',
  pinyin: null,
  definition: null,
  radical: '禾',
  radical_code: '115.3',
  stroke_count: '8',
  hsk_levl: null,
  general_standard_num: null
}
```

**Comment by MagicBOTAlex** [comment]
I am quite late to this but i asked ChatGPT for the pinyin and it says, that those two letters are variants and therefore don't have pinyin. (I used ChatGPT because I can't read Chinese (yet))



Prompt: give me the pinyin of '裏' and '秊'

ChatGPT:
The characters '裏' and '秊' you mentioned are not standard Chinese characters. They appear to be variant or uncommon characters that are not widely used or recognized. Therefore, they do not have standard pinyin transliterations associated with them.

In the context of standard Chinese pinyin, the pinyin system is primarily used to represent the pronunciation of standard Chinese characters based on their official forms. Variant characters, such as '裏' and '秊', may not have established pinyin transliterations.

If you have specific information or context regarding the pronunciation or intended usage of these variant characters, please provide additional details so that I can assist you further.

**Comment by ruddfawcett** [comment]
Hi, thank you for raising the issue. I will close this due to inactivity, and because the dataset should stay true to the original data source.
